version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=incident_admin
      - DB_PASSWORD=incident_password
      - DB_NAME=incident_grade
      - JWT_SECRET=incidencegrade
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=incident_admin
      - POSTGRES_PASSWORD=incident_password
      - POSTGRES_DB=incident_grade
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 